### ISSUE TITLE
Most enjoyable front-end frameworks

### ISSUE THREAD

**Issue by egoist** [IonicaBizau/ama#1]
I've been seen you doing a lot of node.js things, so this is a front-end related question. 😂

eg: React, Angular, Vue, Polymer, Deku etc...

I personally prefer Vue then React. 🤔

- for Vue it had an elegant API and a mild learning curve 🤗
- for React it can render on both server-side and client-side and had a really nice community. 😗

**Comment by IonicaBizau** [comment]
I don't have any favorite framework because, generally, I don't like frameworks. Instead, I like to use small libraries and `require` they are needed.

I did use React and I have to admit that I enjoyed using it: I learned it quickly, but forgot it quickly too. I was not for someone else. :smile: I may use React on the server in the future because I like its idea.

Again, I'm not that much into frameworks because it's not my style. :grin:
