### ISSUE TITLE
What's your advice to become a good programmer?

### ISSUE THREAD

**Issue by gowthamgts** [IonicaBizau/ama#11]
There are plenty of programmers out there in the wild, but not everyone is a great programmer. :disappointed: 

So, what is your advice for a beginner to become a rockstar programmer? :guitar:

**Comment by IonicaBizau** [comment]
*My* advice is below.  📝

There are few points in the following list that are applicable in general (how to be a better human—but they work nicely to help you become a good programmer) and others which are highly tech/programming-related.

 - **Work, experiment, learn from mistakes, repeat**: If you are sure what you're doing is right, keep doing it, even people around you say it's impossible. You may succeed. Work hard. If it's getting complicated, take a piece of paper and draw a scheme of what you want to build there. Then, build it. 🚀

  Obviously, sometimes we do mistakes because we are humans. Don't forget mistakes. Learn from them. If it's the case, share them with others. Next time, be more careful in that direction.  

 - **Do not copy-paste code**: From my experience, I can tell that maintaining copy-wasted code is hard. Extremely hard. Instead of copy-pasting, modularize the stuff. Split it into small and reusable parts (aka modules) and then `require` them where they are needed. If creating a module is not enough, use configurations. Don't use application generators, unless you know what you do. Make sure you can generate them again (especially the documentation) later, without breaking the functionality. Otherwise, you will have to do manual work. 😅

 - **Use the command line**: I recommend using OSX or Linux as operating-system and spending your day in a terminal emulator. [VIM](http://vim.org) is my favourite editor. It works nicely in these terminals.

 - **Read others code**: You will learn a lot by reading code written by others. Code style, optimisations, little tricks etc. 💫

 - **Open-source (almost) everything**: Publish your code on GitHub. Share it with others and let others share it forward. Because you will have to use Git, you will have to learn it. It's cool. ✨

 - **Contribute in open-source**: Find small things to improve in projects on GitHub. Fork them. Hack them, and finally, raise a pull request.

 - **Debug the code. Don’t `console.log`.** Do not pollute the consoles with noisily output just to find specific variable values. Use the available debuggers (e.g. developer tools in the browser, `node debug <script>` in Node.js). It’s very useful to see how the application works step by step and what’s breaking.

 - **Don’t be afraid to debug code written by others.** Often it happens that the bug comes from a module which is not written by you. Just debug it, fix it and send your fix to the author so they can ship it in the next releases.

 - **Eat healthy food and drink good drinks**: There is a strong relation between the food we eat and the way we think. If there is something I really recommend, is to not eat meat at all. As human beings, [we were not designed to eat meat](https://www.biblegateway.com/passage/?search=Gen.1.29&version=NIV). As a vegetarian, I can tell you there are lots of things to eat that are so tasty and keep you healthy. 🍎🍏🍐🍊🍋🍌🍉🍇🍓🍈🍒🍑🍍🍅🍆🌶and others. 😁 Animals are your friends. Don’t eat them.

  Don't drink stuff which is not good for your body: starting with alcoholic drinks (wine, beer etc) to non-natural juices and ending with energy drinks and coffees. Related to these are the different types of drugs which are allowed by the state, but not healthy. Drink water and make homemade fruit juices. They are tastier and way better. 😋

 - **Take time for your family**: Take time to be with your (grand)parents/brothers/sisters/etc. Every day. Life is short, and these moments are precious. ✨ 

 - **Rest**: Sleep ~8 hours a night (few of them before midnight) and wake up early in the morning.

    Bugs are easier to fix in the morning than in the evening/night. 😜 

  Rest ~~one day a week~~ the Saturday. When God created us, He declared the Saturday (7th day of the week) to be for rest. He blessed this day and made it special ([Genesis 2:2-3](https://www.biblegateway.com/passage/?search=Gen.2.2-3&version=NIV)). Enjoy the nature God created for us (don't forget it's affected by 6000 years of sin and it's still beautiful). Take your time to have a special relationship with Him and together with your family (and church community if there is one around). 

 - **Value each moment of your life**: Don't stay inactive. Time is valuable. More than we can realise. Few ideas: make origami animals (optionally, make children around you happier when you wait in a never-ending queue), show people interesting facts (e.g. simple physics-related experiments, tricks etc).

---

Finally, never forget this world is not our home. God is coming soon and the sin will disappear. It won’t be long. ⏳

Even tho, don't get panicked.

Martin Luther was saying:

> Even if I knew that tomorrow the world would go to pieces, I would still plant my apple tree.

So, keep working, while being aware the times we're living. I hope this will help you! 😀

**Comment by gowthamgts** [comment]
Thanks pal... :smile:

**Comment by OksanaBorukh** [comment]
Thanks!

**Comment by Jailo** [comment]
Great advice!

**Comment by israteneda** [comment]
Thank you for your advice.
