### ISSUE TITLE
As a logically minded programmer, what makes you believe in god?

### ISSUE THREAD

**Issue by garygreen** [IonicaBizau/ama#19]
It's clear you are very religious. As a programmer, you need to be logically minded, which means you are good at critically analysing the world in a methodical manner and deducing facts from fiction.

All the evidence we have points towards no deity - religious views are indisputable given all we know in science (the earth is not 6000 years old, nor is it flat, noahs ark is logistically impossible, the list goes on.)

What compelling evidence makes you believe in god, and do you feel there is any strong connection between logically minded people and religious beliefs?

**Comment by IonicaBizau** [comment]
Usual things like the daily sunrise and sunset, the beauty of sky during the night etc etc, all these are clear points to me that there is Someone who is in control.

Every day we build things (particularly software) and, in general, the more complex they are, more time we spend building them. Now think how complex ~~our world~~ the Universe is. How come that we have an author for the smallest `npm` modules but some people say that we came from nowhere?

> and do you feel there is any strong connection between logically minded people and religious beliefs?

Unfortunately I say *no*. What we can see is the actions of a person, but not what's in their mind. They may say they believe something but have an evil plan in their mind. Also, there are many great programmers, scientists etc who do not believe in God. 

I believe the intelligence is a gift from God, and according to [James 1:5](https://www.biblegateway.com/passage/?search=Jas.1.5&version=NIV), we can ask for it. Because the way we were designed, it's up to each one of us to use our intelligence in the direction we want. Also, I believe that there are moments in life when one can see the evidence of God. :blush:

**Comment by dandv** [comment]
@garygreen: Like Ionica, I was also an excellent programmer (2nd place nationwide at the Romanian Olympiad in Informatics), yet I still believed in God, went to church regularly, fasted, and all that nonsense. That went on from 14yo until about 22.

People can compartmentalize in astonishing ways. My father is a medical doctor running clinical trials, and still incredibly religious and dogmatic, despite having no answers to the hard questions about [God](https://web.archive.org/web/20171231000315/http://www.godisimaginary.com/), the [Bible](https://www.evilbible.com/) and [so on](https://www.skepticsannotatedbible.com/).

> As a programmer, you need to be logically minded, which means you are good at critically analysing the world in a methodical manner and deducing facts from fiction.

Nope, nope, nope. As a programmer, you need to be logically-minded when you program. It doesn't mean you're good at critical thinking, it doesn't mean you're good at not being duped, and above all, **it doesn't imply that you've put in the effort to separate facts from fiction**.

You can see this in Ionica's answer to my related question, [Why do you advertise on your GitHub profile that you are a Jesus follower?](https://github.com/IonicaBizau/ama/issues/37), in which I pointed out some sites skeptical of the Bible and God:

> I saw these websites in the past and these are common/classical points raised by non-believers... I do not have the physical time to answer to them, but **I am sure somebody took the time to write about them from the Biblical perspective**.

...and that was enough. It didn't matter if those writings from the Biblical perspective were sound arguments (logically valid, *and* with true premises).

And here,

> Usual things like the daily sunrise and sunset, the beauty of sky during the night etc etc, all these are clear points to me that there is Someone who is in control.

There are obviously simpler explanations for sunrise and sunset (astronomy), the beauty of anything (see [this video](https://youtu.be/-O5kNPlUV7w)), without necessitating an astonishingly complex (and unexplained) "Anyone" in control. But one can see that the search for an explanation was simply not taken any farther than "God did it". (Which doesn't explain anything, because it does not have any predictive power, while astronomy has, and doesn't survive [Occam's razor](https://github.com/IonicaBizau/ama/issues/16#issuecomment-449479578)).

As a [virus of the mind](https://en.wikipedia.org/wiki/Virus_of_the_Mind), religion is immune to logic.

I've even [asked](https://www.youtube.com/watch?v=TjxZ6MrBl9E) Richard Dawkins, "what would be ONE question you'd ask a believer in order to shake their beliefs?". There isn't any.
