### ISSUE TITLE
Q : What is the best place for web developers ? 

### ISSUE THREAD

**Issue by Noor-ALHassan** [IonicaBizau/ama#2]
Hello ,

I need best place to communicate with another developer and get answer to our questions . 
 

Thank You A lot .

**Comment by IonicaBizau** [comment]
I would say GitHub issue tracker. :octocat:

It depends on the context. If you want to talk with another developer about things that are *not* related to a specific project, then a chat app would be perfect. :speech_balloon: I have been using Google Hangouts for a long time.

When there are general questions about specific projects hosted on GitHub, I recommend opening issues because they are visible to everyone that has access to the project. Also, inline comments are cute too.
