### ISSUE TITLE
Where is your source for ideas?

### ISSUE THREAD

**Issue by dance2die** [IonicaBizau/ama#24]
I was reading your answer on your [daily routine](https://github.com/IonicaBizau/ama/issues/3) and can't help but notice you mentioning about `ideas`.

I see so many repos and wondering `where is your source of idea?`
Books? Blogs?, etc.

Would you recommend some (*all* preferrably :smile: ) `resources` of your ideas, as well?

Thank you~

**Comment by IonicaBizau** [comment]
Books? Yes! Blogs? Yes!

Sometimes I get ideas **when I'm working** on something and I realize that I could extend something making it more generic.

For example, [`scrape-it`](https://github.com/IonicaBizau/scrape-it) was something I had in mind for a long time before building it. When I finally decided to build it, I thought: *Alright, maybe I will build it step by step and write a tutorial as well!*

So, while writing [How to write a web scraper in Node.js](https://ionicabizau.net/blog/30-how-to-write-a-web-scraper-in-node-js), I created [`cheerio-req`](https://github.com/IonicaBizau/cheerio-req/) and wrote some small snippets (used in the post) which after few minutes were the core part of `scrape-it`.

I remember I published that module on a Thursday or Friday, and on Friday afternoon I left a link on ProductHunt about it. Saturday evening, after the resting, I checked my emails and I was surprised to find lots of emails from Twitter, ProductHunt, and GitHub about `scrape-it`! It was my first project who went kinda viral on ProductHunt.

Truth is I didn't make a lot of research of existing scrapers in the Node.js community, so I just built one following the JSON syntax ideas I had in my head. 😁  

---

Also, ideas come [when I'm resting or relaxing](https://www.quora.com/Why-do-great-ideas-come-when-you-are-on-a-toilet-or-in-a-bath). Sometimes, just being in nature or [doing rock balancing](https://twitter.com/search?f=tweets&q=from:ionicabizau%20rockbalancing&src=typd)—in fact taking few moments for me, to not get distracted by phone notifications, emails etc—helps me too!

I heard about a programmer who before solving a difficult problem, goes to take a few minutes of rest in their hammock and just sits there not thinking about that difficult problem that needs to be solved.

Because I believe we were designed to have Saturday as a day of rest, I end my work few hours before Friday's sunset and coming back after the Saturday's sunset. During this time I put my phone on Airplane mode (unless I'm traveling and have to send `ping`s to my brothers/parents that everything is fine :grin:) and I try to not think of any business/work/coding related things. 

---

Daily I get two newsletters:

 - [GitHub Explore](https://github.com/explore)
 - [ProductHunt](https://www.producthunt.com)

I read quickly the titles and open those who seem very interesting.

[The Changelog](https://changelog.com) twitter's feed is quite interesting (they share interesting projects) and sometimes I listen to their podcasts.

---

Along with programming I do [other random stuff](https://patreon.com/johnnyb) such as playing piano, experiments including chemistry, high voltage, DIY projects etc. Probably, those help too! 😁 

What I noticed is that smaller ideas build greater ideas: like the `npm` modularization. 😂 It doesn't matter if an idea is a tiny one (e.g. a small project). Just build it. Share it. Maybe after one week, you will get another small one. And maybe after four weeks, a bigger one will come just because previously you put an effort in appreciating the small things. 🚀 

Putting love in whatever you do matters. Scripture says that *Whatever your hand finds to do, do it with your might* (Ecclesiastes 9:10) and I found that to be correct!

Finally, I just leave another link to a [previous interview](https://www.todaysoftmag.com/article/2142/interview-with-ionica-bizau) where you can read my answers to some related questions. 📝
