### ISSUE TITLE
Why do you use emojis everywhere?

### ISSUE THREAD

**Issue by nieltg** [IonicaBizau/ama#27]
Hi there!
I was searching for a new package name before, then I found your GitHub profile while I was checking if any of my proposed names has been taken or not on [npmjs.com](https://www.npmjs.com/search?q=overlap).

While I was reading entries (or, maybe issues :grin:) on your **ama**, I noticed that you use emojis a lot. Then, I found a link to your blog. While I was opening one of your post, I noticed that you also use emojis in your blog.

This stalking journey made me curious about your emoji usages.

1. Why do you use emojis everywhere?
2. What are your favorite emojis?
3. How do you put emojis in your post?
a. Do you remember emoji codes?
b. Do you open emoji cheat sheet like this [one](https://gist.github.com/rxaviers/7360908) frequently?
c. Or do you just let GitHub emoji auto-completion kicks in while typing emojis?

Pardon for my not-really-important questions (it's not about amazing coding things, etc)
but since this is **ama**, I asked these questions while I was practicing my English. :grin:

Happy new year 2018. God bless you.
Thank you.

**Comment by IonicaBizau** [comment]
Indeed, I have [quite a few emoji-related projects](https://github.com/IonicaBizau?utf8=%E2%9C%93&tab=repositories&q=emoji&type=&language=).

> Why do you use emojis everywhere?

I feel they make the content look better and more colorful. Also, I guess it helps the reader to understand the content quickly (e.g. if they see a `:heart:`, they will probably think that section is love-related). :memo: 

I have a typewriter around, and when I use it to write letters, I don't use emojis. However, if I really want to add a :heart: symbol, I would use the `&lt;3`, since it doesn't have a `<` character. :joy: 

In formal documents, I don't use them. :scroll: 

> What are your favorite emojis?

:joy: :grin: :blush: :rocket: :sparkling_heart: :heart_eyes: :sparkles: 

(pretty much in this order :joy:)

> How do you put emojis in your post?

Using `:emoji_codes:`, which are interpreted by [this](https://github.com/Bloggify/emoji) plugin.

> a. Do you remember emoji codes?

Yup, yup! :grin: 

> b. Do you open emoji cheat sheet like this one frequently?

When I don't remember a good emoji, I search it using one of these cool apps:

 - https://emoji.muan.co/ by @muan
 - https://emoji.js.org/ by @egoist

> c. Or do you just let GitHub emoji auto-completion kicks in while typing emojis?

The GitHub emoji suggestions are neat as well! :sparkles: 

----

Wish you a happy new year too and many blessings from God! :pray:

**Comment by dandv** [comment]
Do you still believe in :godmode:  as much as ~4 years ago :smiley:  but anyway, KDE has an Emoji Selector easily invoked with <kbd>Super + .</kbd> :nerd_face:

**Comment by IonicaBizau** [comment]
@dandv Must say that sometimes I find easier using "emojis" like `:-)`, `<3`, `:D` etc., than the actual emojis, but yes, I still love emojis. 🍀
