### ISSUE TITLE
What is your daily routine ? 

### ISSUE THREAD

**Issue by sureshatta** [IonicaBizau/ama#3]
I was wondering how you manage your time ?  

You are on stackoverflow. You are on CodeMentor. You are on GitHub (unlike me), Hackhands, linux forums ..ah what not and where not. As I know little things about you, you work for a company as well.

But how you manage your time ? What all techniques you use to maintain the time slots ?

Eagerly waiting for the answer. Hope that change my life too :dancers:

**Comment by IonicaBizau** [comment]
> I was wondering how you manage your time ?

(Currently,) I don't have a schedule that I follow. I do a lot of random things, so I just **prioritize** them based on multiple parameters: the requester (e.g. if it's a good friend then I switch on that task quickly), fun, utility, profit etc.

For example, while I'm doing open-source stuff, I keep a [CodeMentor](https://www.codementor.io/johnnyb) tab opened. When somebody needs help, I stop working on my OSS projects and help her/him.

Also, when I get an idea, I note it down using [`idea`](https://github.com/IonicaBizau/idea). Then when I'm running without of work I check my saved ideas and start implementing the best one. :bulb: 

I try to keep my schedule flexible. When working for a company it's important that I don't work full time because it's just too much for me.

**Sleep time is important:** I usually go to bed at 10 PM and wake up at 5:50 AM. I consider night time is for sleep and daytime is for work.

**Rest is important:** I work 6 days a week (Sunday-Friday) and I stop working ~1-2 hours before Friday's sunset and start working again after Saturday's sunset, because I do believe Saturday is a special day (see [Genesis 2:3](https://www.biblegateway.com/passage/?version=NCV&search=Genesis%202), [Exodus 20:8-11](https://www.biblegateway.com/passage/?version=NCV&search=Exodus%2020)), so I never work Saturdays.

**Breaks are important:** I often make breaks between my tasks because they are good. I usually play piano during these short breaks. :musical_keyboard: 

Hope this helps. :grin:

**Comment by egoist** [comment]
@IonicaBizau Very similar to you, except the sleep time 😂 Wish to change that soon... 🙏

**Comment by IonicaBizau** [comment]
:joy:

**Comment by Piicksarn** [comment]
@IonicaBizau, you are really amazing!!:sparkles::sparkles::sparkles:

**Comment by IonicaBizau** [comment]
Thank you, @Piicksarn! :grin:
