### ISSUE TITLE
How do you create logos for your modules? Just like you made for "ideas"?

### ISSUE THREAD

**Issue by amitmerchant1990** [IonicaBizau/ama#9]

**Comment by IonicaBizau** [comment]
That's a good question! There we go:

 - :computer: **Software**: I use [InkScape](https://inkscape.org/en/) to create SVG images. Usually the ones used in projects have the size of `900x400`.
 - :art: **Colors**: [Flat Colors](http://flatuicolors.com/) are my favorite colors! :grin: 
 - :octocat: **Icons**: I really like [GitHub's Octicons](https://octicons.github.com/), falling back to [FontAwesome](https://github.com/encharm/Font-Awesome-SVG-PNG). I usually use them in my project *logos*.
 - :abc: **Fonts**: The fonts used in displaying the text are from [Google Fonts](https://github.com/google/fonts).
 - :rocket: Finally, I publish them in [IonicaBizau/resources](https://github.com/IonicaBizau/resources) repository.

**Comment by amitmerchant1990** [comment]
Hi @IonicaBizau , can you give me a tutorial link or any resource which I can follow step by step to create logos?

**Comment by IonicaBizau** [comment]
@amitmerchant1990 Similar to my answer to #4, I recommend you to learn by doing. Install InkScape and try playing around. First time is confusing, but you will quickly find solutions. I really like InkScape. I was using since the days when it was very unstable. Now it's a smooth experience to work with it. :rocket: 

Here is my color palette I use: https://github.com/IonicaBizau/dotfiles/blob/master/inkscape/FlatUI-palette.gpl :art: 

Also, I'm not that good in designing logos. I just do it for fun (especially for my projects), mostly by combining icons created by others (e.g. Octicons, font-awesome etc).

**Comment by amitmerchant1990** [comment]
Okay great! Thanks! :smile:

**Comment by egoist** [comment]
Seems InkScape is pretty good, personally I use [sketch](https://www.sketchapp.com/) to draw logos and prototype web apps, pretty easy 😅
